### ISSUE TITLE
поч репа пустая

### ISSUE THREAD

**Issue by A-D-O-L-F-H-I-T-L-E-R** [DiscordHitlerBot/Daggeestaen#1]
долбоёб артём давай ридми хотяб сделай

**Comment by cafeed28** [comment]
я делою

**Comment by 15baller** [comment]
Я однажды лишь ебался

**Comment by A-D-O-L-F-H-I-T-L-E-R** [comment]
где и зачем с как и кем

**Comment by 15baller** [comment]
не важно я да и не помню

**Comment by A-D-O-L-F-H-I-T-L-E-R** [comment]
я пидорас в день тот очень был

**Comment by cafeed28** [comment]
и не важен пол волос и цвет и глаз

**Comment by A-D-O-L-F-H-I-T-L-E-R** [comment]
да пидорас возможно я

**Comment by 15baller** [comment]
но ведь раз лишь был это...

**Comment by A-D-O-L-F-H-I-T-L-E-R** [comment]
у у пососи у у да богатый денег коробка я уёбок

**Comment by A-D-O-L-F-H-I-T-L-E-R** [comment]
я однался лишь ебажды

**Comment by 15baller** [comment]
![unknown-4](https://user-images.githubusercontent.com/118118572/210487825-88f611ca-927c-48f3-9bc8-2ecf096e723c.png)

**Comment by cafeed28** [comment]
вобщето не пустая
